name: notyai
description: "Ses Odaklı Akıllı Ajanda ve Yerel Takvim Asistanı"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Durum & Tema Yönetimi
  provider: ^6.1.2
  shared_preferences: ^2.2.2

  # Ses Tanıma (Speech-to-Text) & İzinler
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1

  # Yapay Zeka (Gemini API) & Ağ
  http: ^1.2.1

  # Cihaz Yerel Takvimi (Samsung, Xiaomi, Honor, Apple, Google vb.)
  device_calendar: ^4.3.2

  # Bildirimler & Saat Dilimleri
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  flutter_timezone: ^2.0.0

  # Tipografi & Simgeler
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
