allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

subprojects {
    plugins.withId("com.android.library") {
        android {
            compileSdk 34
            defaultConfig {
                minSdk 23
                targetSdk 34
            }
        }
    }
}
